# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(230, 160)
        MainWindow.setMinimumSize(QtCore.QSize(230, 160))
        MainWindow.setMaximumSize(QtCore.QSize(230, 160))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 211, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_name.setStyleSheet("")
        self.line_name.setObjectName("line_name")
        self.gridLayout.addWidget(self.line_name, 0, 0, 1, 2)
        self.line_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_password.setStyleSheet("")
        self.line_password.setObjectName("line_password")
        self.gridLayout.addWidget(self.line_password, 1, 0, 1, 2)
        self.btn_login = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_login.setStyleSheet("background-color: #ffffff;")
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 2, 0, 1, 1)
        self.btn_register = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_register.setStyleSheet("background-color: #ffffff;")
        self.btn_register.setObjectName("btn_register")
        self.gridLayout.addWidget(self.btn_register, 2, 1, 1, 1)
        self.btn_change_pass = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_change_pass.setObjectName("btn_change_pass")
        self.gridLayout.addWidget(self.btn_change_pass, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход"))
        self.line_name.setPlaceholderText(_translate("MainWindow", "Login..."))
        self.line_password.setPlaceholderText(_translate("MainWindow", "Password..."))
        self.btn_login.setText(_translate("MainWindow", "SIGN IN"))
        self.btn_register.setText(_translate("MainWindow", "SIGN UP"))
        self.btn_change_pass.setText(_translate("MainWindow", "Forgot password?"))
