# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pass_change.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Password_Change(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(310, 240)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 291, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_current_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_current_password.setObjectName("line_current_password")
        self.gridLayout.addWidget(self.line_current_password, 1, 0, 1, 1)
        self.line_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_login.setObjectName("line_login")
        self.gridLayout.addWidget(self.line_login, 0, 0, 1, 1)
        self.line_new_pass_confirm = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_new_pass_confirm.setObjectName("line_new_pass_confirm")
        self.gridLayout.addWidget(self.line_new_pass_confirm, 3, 0, 1, 1)
        self.line_new_pass = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_new_pass.setObjectName("line_new_pass")
        self.gridLayout.addWidget(self.line_new_pass, 2, 0, 1, 1)
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setGeometry(QtCore.QRect(10, 210, 289, 23))
        self.btn_save.setObjectName("btn_save")
        self.lbl_error = QtWidgets.QLabel(Form)
        self.lbl_error.setGeometry(QtCore.QRect(10, 190, 289, 16))
        self.lbl_error.setObjectName("lbl_error")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.line_current_password.setPlaceholderText(_translate("Form", "Current password..."))
        self.line_login.setPlaceholderText(_translate("Form", "Login..."))
        self.line_new_pass_confirm.setPlaceholderText(_translate("Form", "New password (repeat)..."))
        self.line_new_pass.setPlaceholderText(_translate("Form", "New password..."))
        self.btn_save.setText(_translate("Form", "Save"))
        self.lbl_error.setText(_translate("Form", "TextLabel"))
