# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(239, 279)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 0, 221, 281))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_login = QtWidgets.QLineEdit(self.widget)
        self.line_login.setObjectName("line_login")
        self.gridLayout.addWidget(self.line_login, 0, 0, 1, 1)
        self.line_password = QtWidgets.QLineEdit(self.widget)
        self.line_password.setObjectName("line_password")
        self.gridLayout.addWidget(self.line_password, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.line_last_name = QtWidgets.QLineEdit(self.widget)
        self.line_last_name.setObjectName("line_last_name")
        self.gridLayout.addWidget(self.line_last_name, 3, 0, 1, 1)
        self.line_name = QtWidgets.QLineEdit(self.widget)
        self.line_name.setObjectName("line_name")
        self.gridLayout.addWidget(self.line_name, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 1)
        self.line_born_date = QtWidgets.QLineEdit(self.widget)
        self.line_born_date.setObjectName("line_born_date")
        self.gridLayout.addWidget(self.line_born_date, 6, 0, 1, 1)
        self.line_born_place = QtWidgets.QLineEdit(self.widget)
        self.line_born_place.setObjectName("line_born_place")
        self.gridLayout.addWidget(self.line_born_place, 7, 0, 1, 1)
        self.line_phone = QtWidgets.QLineEdit(self.widget)
        self.line_phone.setObjectName("line_phone")
        self.gridLayout.addWidget(self.line_phone, 8, 0, 1, 1)
        self.btn_save = QtWidgets.QPushButton(self.widget)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 9, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.line_login.setPlaceholderText(_translate("Form", "Login..."))
        self.line_password.setPlaceholderText(_translate("Form", "Password..."))
        self.line_last_name.setPlaceholderText(_translate("Form", "Last name..."))
        self.line_name.setPlaceholderText(_translate("Form", "Name..."))
        self.line_born_date.setPlaceholderText(_translate("Form", "Date of Birth..."))
        self.line_born_place.setPlaceholderText(_translate("Form", "Born place..."))
        self.line_phone.setPlaceholderText(_translate("Form", "Phone Number..."))
        self.btn_save.setText(_translate("Form", "Сохранить"))
